spring.config.import=optional:file:./.env[.properties]

spring.application.name=back-end

# DATASOURCE
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.id.new_generator_mappings=false
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# JWT
security.jwt.secret=${JWT_SECRET}
security.jwt.issuer=barbearia-backend
security.jwt.expiration-seconds=3600



# Configuração provisória da agenda

barbearia.agenda.fuso-horario=America/Sao_Paulo

barbearia.agenda.horario-abertura=09:00
barbearia.agenda.horario-fechamento=18:00

barbearia.agenda.dias-atendimento=MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY

barbearia.agenda.intervalo-habilitado=false
barbearia.agenda.intervalo-inicio=12:00
barbearia.agenda.intervalo-fim=13:00

# barbearia.agenda.intervalo-horarios=1m
barbearia.agenda.antecedencia-minima=1h
barbearia.agenda.antecedencia-maxima=30d